name: Daily News Summary  

on:  
  schedule:  
    - cron: '0 12 * * *'  # Runs every day at 12 PM UTC  
  workflow_dispatch:  # Allows manual triggering  

jobs:  
  fetch-news:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v3  

      - name: Set Up Python  
        uses: actions/setup-python@v3  
        with:  
          python-version: '3.9'  # Adjust version if needed  

      - name: Install Dependencies  
        run: |  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  

      - name: Fetch Latest News  
        run: python fetch_news.py  # ✅ This ensures the script runs  

      - name: Commit and Push Changes  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |  
          git config --global user.name "github-actions"  
          git config --global user.email "github-actions@github.com"  
          git pull --rebase origin main  
          git add .  
          git commit -m "Automated daily news summary update" || echo "No changes to commit"  
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/blbenton/daily-news-brief.git main  
