- name: Generate News Summary
  run: |
    curl -o news_summary.txt "YOUR_CUSTOM_CHATGPT_SUMMARY_URL"

- name: Debug: Show File Contents
  run: cat news_summary.txt

- name: Send Email with News Summary
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 587
    username: ${{ secrets.EMAIL_USERNAME }}
    password: ${{ secrets.EMAIL_PASSWORD }}
    subject: "Your Daily News Brief"
    body: "Attached is your latest news summary."
    to: "blbenton@gmail.com"
    from: "Daily News Bot"
    attachments: "news_summary.txt"
